spring.application.name=VietFresh_Hub
server.port=8080

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=VietFresh_Hub;encrypt=false
spring.datasource.username=sa
spring.datasource.password=123

spring.jpa.properties.hibernate.hbm2ddl.auto=validate
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.mode=HTML
spring.thymeleaf.cache=false
spring.banner.charset=utf-8
